config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  shallow do
    resources :groups do
      resources :decks do
        resources :flashcards
      end
    end
  end


  root "groups#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :group
  has_many :flashcards, dependent: :destroy
  has_many :user_deck_stats, dependent: :destroy
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  belongs_to :deck
  has_many :user_flashcard_progresses, dependent: :destroy
  has_rich_text :body
  validates :title, :body, :deck, presence: true
  broadcasts_to :deck
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships, dependent: :destroy
  has_many :decks, dependent: :destroy
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memberships
  has_many :groups, through: :memberships
  has_many :decks, through: :groups
  has_many :user_flashcard_progresses
  has_many :user_deck_stats

  after_create :create_private_group_and_deck

  def create_private_group_and_deck
    default_group = Group.create!(name: "Example Group")
    default_group.users << self
    default_group.decks.create!(name: "Example Deck")
  end


  def has_access_to_flashcard?(flashcard)
    flashcard.deck.group.users.include?(self)
  end

  def has_access_to_deck?(deck)
    deck.group.users.include?(self)
  end

  def has_access_to_group?(group)
    group.users.include?(self)
  end
end

app/models/user_deck_stat.rb
class UserDeckStat < ApplicationRecord
  belongs_to :user
  belongs_to :deck
end

app/models/user_flashcard_progress.rb
class UserFlashcardProgress < ApplicationRecord
  belongs_to :user
  belongs_to :flashcard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


    private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back_or_to(root_path)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[create]
  before_action :set_deck, only: %i[show edit update destroy]

  def show
    authorize @deck
    @new_flashcard = Flashcard.new(deck: @deck)
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(params.expect!(deck: [ :name, :group_id ]))
    authorize @deck.group if @deck.group
    if @deck.save
      redirect_to @deck
    else
      flash[:alert] = @deck.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @deck
  end

  def update
    authorize @deck
    if @deck.update(params.expect!(deck: [ :name ]))
      redirect_to @deck
    else
      flash[:alert] = @deck.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @deck
    @deck.destroy
    redirect_to @deck.group
  end

  private
    def set_deck
      @deck = Deck.find(params[:id])
      @group = @deck.group
    end
    def set_group
      @group = Group.find params[:group_id]
    end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_deck_and_group, only: %i[create]
  before_action :set_flashcard, only: %i[show edit update destroy]


  def show
    authorize @flashcard
  end

  def create
    authorize @deck
    flashcard = Flashcard.new flashcard_params
    flashcard.deck = @deck
    if flashcard.save
      @deck.flashcards << flashcard
      return
    end
    flash[:alert] = flashcard.errors.full_messages.to_sentence
    @flashcard = flashcard
    redirect_to @deck, status: :unprocessable_entity
  end

  def edit
  end

  def update
    authorize @flashcard
    if @flashcard.update(flashcard_params)
      redirect_to @flashcard
    else
      render :edit, status: :unprocesable_entity
    end
  end

  def destroy
    @flashcard.destroy
    redirect_to @deck
  end

  private
    def set_flashcard
      @flashcard = Flashcard.find(params[:id])
      @deck = @flashcard.deck
      @group = @deck.group
    end
    def set_deck_and_group
      @deck = Deck.find(params[:deck_id])
      @group = @deck.group
    end
    def flashcard_params
      params.expect!(flashcard: [ :title, :body ])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = current_user.groups
  end

  def show
    authorize @group
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @group.users << current_user
      redirect_to @group
    else
      flash[:alert] = @group.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    authorize @group
    if @group.update(group_params)
      redirect_to @group
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @group
    @group.destroy
    redirect_to groups_path
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.expect!(group: [ :name ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/decks/show.html.erb
<%= turbo_stream_from @deck %>

<div class="flex justify-center flex-col w-2/3 mt-2 gap-4">
  <div class="w-full flex justify-between items-center">
    <div class="">
        <div class="">
          <p class="text-2xl"><%= @deck.name %></p>
          <p class="">Placeholder for Deck descriptions</p>
        </div>
    </div>
    <div>
      <%= link_to "Edit", edit_deck_path(@deck), class: "link"%>
      <%= button_to "Delete", @deck, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "link" %>
    </div>
  </div>
  <div id="flashcards" class="w-4/5 self-center"> 
    <%= render "flashcards/flashcards", deck: @deck %>
  </div>

  <div id="new flashcards" class="w-4/5 self-center">
    <%= render "flashcards/form", deck: @deck, flashcard: Flashcard.new(deck: @deck) %>
</div>

app/views/flashcards/_flashcard.html.erb
<div class="w-full flex justify-between items-center">
  <div class="">
    <%= link_to flashcard.title, flashcard, class: "link" %>
  </div>
  <div class="">
    <%= link_to "delete", flashcard, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "link" %>
  </div>
</div>

app/views/flashcards/_flashcards.html.erb
    <div class="flex justify-between items-center">
      <div class="">
        <div class="">
          <p class="text-2xl">flashcards</p>
          <p class="">Flashcards of <%= @deck.name %></p>
        </div>
      </div>
      <div class="">
        <%= link_to "Create Flashcard", new_deck_flashcard_path(@deck), class: "link" %>
      </div>
    </div>
    <% @deck.flashcards.each do |flashcard| %>
      <%= render "flashcards/flashcard", flashcard: flashcard %>
    <% end %>

app/views/flashcards/_form.html.erb
<%= form_with model: flashcard, url: (flashcard.new_record? ? deck_flashcards_path(deck, flashcard) : flashcard_path(flashcard)) do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body, style: "display: block" %>
        <%= form.rich_text_area :body %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/flashcards/edit.html.erb
<h1>Edit Flashcard</h1>

<%= render "form", flashcard: @flashcard%>
<%= link_to "Back", :back %>

app/views/flashcards/show.html.erb
<p>Deck:<%= link_to @flashcard.deck.name, @flashcard.deck %></p>
<div class="card self-center w-1/3">
  <header class="card-header">
    <p class="card-header-title"><%= @flashcard.title %>
  </header>
  <div class="card-content">
    <div class="content">
      <%= @flashcard.body %>
    </div>
  </div>
<% if user_signed_in? %>
  <footer class="card-footer">
    <%= link_to "Edit", [:edit, @flashcard], class: "card-footer-item" %>
    <%= link_to "Delete", @flashcard, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "card-footer-item" %>

  </footer>
<% end %>

app/views/groups/index.html.erb
<div class="flex justify-center flex-col w-2/3 mt-2  ">
  <div class="w-full flex justify-between items-center">
    <div class="">
        <div class="">
          <p class="text-2xl">Groups</p>
          <p class="">All Groups you have access to!</p>
        </div>
    </div>
    <div class="">
      <%= link_to "Create Group", new_group_path, class: "link" %>
    </div>
  </div>
  <div id="groups" >
    <% @groups.each do |group| %>
        <div class="w-full flex justify-between items-center">
          <div class="">
              <%= link_to group.name, group, class: "link" %>
          </div>
          <div class="">
            <%= link_to "delete", group, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "link" %>
          </div>
        </div>
    <% end %>
</div>

app/views/groups/show.html.erb
<div class="flex justify-center flex-col w-2/3 mt-2  ">
  <div class="w-full flex justify-between items-center">
    <div class="">
        <div class="">
          <p class="text-2xl"><%= @group.name %></p>
          <p class="">Placeholder for Group descriptions</p>
        </div>
    </div>
    <div>
      <%= link_to "Edit", edit_group_path(@group), class: "link"%>
      <%= button_to "Delete", @group, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "link" %>
    </div>
  </div>
  <div id="decks" class="w-4/5 self-center mt-4" >
    <div class="flex justify-between items-center">
      <div class="">
        <div class="">
          <p class="text-2xl">Decks</p>
          <p class="">Decks of <%= @group.name %></p>
        </div>
      </div>
      <div class="">
        <%= link_to "Create Deck", new_group_deck_path(@group), class: "link" %>
      </div>
    </div>
    <% @group.decks.each do |deck| %>
      <div class="w-full flex justify-between items-center">
        <div class="">
          <%= link_to deck.name, deck, class: "link" %>
        </div>
        <div class="">
          <%= link_to "delete", deck, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation_bar.html.erb
<nav role="navigation" aria-label="main navigation" class="">
  <div class="flex flex-wrap items-center justify-between mx-auto p-4">
  <div class="">
    <%= link_to "Home", root_path, class:"link" %>
  </div>
  <div class="">
    <%= link_to "sign out", destroy_user_session_path, data: { turbo_method: :delete, turb_confirm: "Are you sure?" }, class:"link"  if user_signed_in?%>
    <% if !user_signed_in? %>
      <%= link_to "sign up", new_user_registration_path, class:"link" %>
      <%= link_to "sign in", new_user_session_path, class:"link" %>
    <% end %>
  </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flashcards" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">


    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%#= stylesheet_link_tag :app, "data-turbo-track": Rails.env.production? ? "reload" : "" %>
    <%= javascript_importmap_tags %>

  </head>

  <body class="bg-background">
    <%= render "layouts/navigation_bar" %>
  <% flash.each do |type, msg| %>
    <div class="<%= type %>">
      <%= msg %>
    </div>
  <% end %>
    <div class="w-full flex justify-center">
      <%= yield %>
    </div>
  </body>
</html>